/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrbanRouteImport } from './routes/urban'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as IndustrialRouteImport } from './routes/industrial'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as ChangeSamplesRouteImport } from './routes/change-samples'
import { Route as AgriculturalRouteImport } from './routes/agricultural'
import { Route as IndexRouteImport } from './routes/index'

const UrbanRoute = UrbanRouteImport.update({
  id: '/urban',
  path: '/urban',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrialRoute = IndustrialRouteImport.update({
  id: '/industrial',
  path: '/industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeSamplesRoute = ChangeSamplesRouteImport.update({
  id: '/change-samples',
  path: '/change-samples',
  getParentRoute: () => rootRouteImport,
} as any)
const AgriculturalRoute = AgriculturalRouteImport.update({
  id: '/agricultural',
  path: '/agricultural',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agricultural': typeof AgriculturalRoute
  '/change-samples': typeof ChangeSamplesRoute
  '/comparison': typeof ComparisonRoute
  '/industrial': typeof IndustrialRoute
  '/prices': typeof PricesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/urban': typeof UrbanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agricultural': typeof AgriculturalRoute
  '/change-samples': typeof ChangeSamplesRoute
  '/comparison': typeof ComparisonRoute
  '/industrial': typeof IndustrialRoute
  '/prices': typeof PricesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/urban': typeof UrbanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agricultural': typeof AgriculturalRoute
  '/change-samples': typeof ChangeSamplesRoute
  '/comparison': typeof ComparisonRoute
  '/industrial': typeof IndustrialRoute
  '/prices': typeof PricesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/urban': typeof UrbanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agricultural'
    | '/change-samples'
    | '/comparison'
    | '/industrial'
    | '/prices'
    | '/sitemap.xml'
    | '/story'
    | '/urban'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agricultural'
    | '/change-samples'
    | '/comparison'
    | '/industrial'
    | '/prices'
    | '/sitemap.xml'
    | '/story'
    | '/urban'
  id:
    | '__root__'
    | '/'
    | '/agricultural'
    | '/change-samples'
    | '/comparison'
    | '/industrial'
    | '/prices'
    | '/sitemap.xml'
    | '/story'
    | '/urban'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgriculturalRoute: typeof AgriculturalRoute
  ChangeSamplesRoute: typeof ChangeSamplesRoute
  ComparisonRoute: typeof ComparisonRoute
  IndustrialRoute: typeof IndustrialRoute
  PricesRoute: typeof PricesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  UrbanRoute: typeof UrbanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urban': {
      id: '/urban'
      path: '/urban'
      fullPath: '/urban'
      preLoaderRoute: typeof UrbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrial': {
      id: '/industrial'
      path: '/industrial'
      fullPath: '/industrial'
      preLoaderRoute: typeof IndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-samples': {
      id: '/change-samples'
      path: '/change-samples'
      fullPath: '/change-samples'
      preLoaderRoute: typeof ChangeSamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultural': {
      id: '/agricultural'
      path: '/agricultural'
      fullPath: '/agricultural'
      preLoaderRoute: typeof AgriculturalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgriculturalRoute: AgriculturalRoute,
  ChangeSamplesRoute: ChangeSamplesRoute,
  ComparisonRoute: ComparisonRoute,
  IndustrialRoute: IndustrialRoute,
  PricesRoute: PricesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  UrbanRoute: UrbanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
